---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Internet Gateway & Route"

Parameters:
  NetworkStack:
    Type: "String"
    Description: "Network stack to apply"

Resources:

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-VpcId

  publicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-VpcId
      Tags:
      - Key: Name
        Value: Dmz Routes
      - Key: Scope
        Value: public

  publicRouteToInternet:
    DependsOn: InternetGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref publicRouteTable

  publicRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref publicRouteTable
      SubnetId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-DmzSubnetAId

  publicRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref publicRouteTable
      SubnetId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-DmzSubnetBId

 # #NatGateway:
 #   DependsOn: InternetGatewayAttachment
 #   Type: AWS::EC2::NatGateway
 #   Properties:
 #     AllocationId: !GetAtt ElasticIP.AllocationId
 #     SubnetId:
 #       Fn::ImportValue:
 #         !Sub ${NetworkStack}-DmzSubnetAId

#  ElasticIP:
#    Type: AWS::EC2::EIP
#    Properties:
#      Domain: vpc

  privateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-VpcId
      Tags:
        - Key: Name
          Value: Private Routes
        - Key: Scope
          Value: private

#  privateRouteToInternet:
#      Type: AWS::EC2::Route
#      Properties:
#        RouteTableId: !Ref privateRouteTable
#        DestinationCidrBlock: 0.0.0.0/0
#        NatGatewayId: !Ref NatGateway

  privateRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref privateRouteTable
      SubnetId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-SubnetNodesAId
  privateRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref privateRouteTable
      SubnetId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-SubnetNodesBId

